version: "3"

services:
    client:
        build: ./client
        command: npm start
        ports: 
            - "3000:3000"
        volumes: 
            - ./client:/usr/src/client
            - /usr/src/client/node_modules
        environment:
            REACT_APP_API_HOST: server
        depends_on: 
            - server
        links: 
            - server
    server:
        build: ./server
        command: npm start
        restart: on-failure:10
        ports: 
            - "3333:3333"
        volumes: 
            - ./server:/usr/src/by_coders/server
            - /usr/src/by_coders/server/node_modules
        environment:
            DB_HOST: postgres
            DB_USER: postgres
            DB_PASSWORD: mysecretpassword
            DB_NAME: by_coders
        depends_on: 
            - postgres
    postgres:
        image: postgres:12
        ports: 
            - "5433:5432"
        environment:
            POSTGRES_PASSWORD: mysecretpassword
            POSTGRES_USER: postgres
